version: "3.9"
services: 
  server:
    build: ./backend-server
    ports:
    - "8080:8080"
    volumes:
    - ./backend-server:/server
    environment:
      FLASK_ENV: development
  web:
    build: ./detection
    ports:
      - "5173:5173"
    volumes:
      - ./detection:/detection/src/app
    depends_on:
      - server


